steps:
- name: node:10.15.1
  entrypoint: npm
  args: ["install"]
- name: node:10.15.1
  entrypoint: npm
  args: ["run", "build"]
- name: "gcr.io/manifest-reach-271300/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"